version: "3"
services:
  db:
    image: mysql:latest
    container_name: db-registration-service-7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=healthcare
      - MYSQL_DATABASE=db_registration_service
    volumes:
      - ./setup-mysql.sh:/setup-mysql.sh
